[project]
name = "napari-bruce"
dynamic = ["version"]
description = "A napari plugin for drawing PALM RoboSoftware elements using StarDist segmentation"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "Benjamin Vallin", email = "ben.vallin@gmail.com" }]

classifiers = [
  "Framework :: napari",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: MIT License",
  "Intended Audience :: Science/Research",
]

dependencies = [
  "napari",
  "PyQt5",
  "qtpy",
  "numpy==1.26.4",
  "opencv-python-headless",
  "ome-types",
  "tifffile",
  "pandas",
  "matplotlib",
  "csbdeep",
  "stardist",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = false

[tool.setuptools.dynamic]
version = {attr = "napari_bruce.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["napari_bruce.dev*"]

[tool.setuptools.package-data]
"napari_bruce" = [
  "*.yaml",
  "bioformats/bioformats_package.jar",

  "stardist_models/stardist_th/config.json",
  "stardist_models/stardist_th/thresholds.json",
  "stardist_models/stardist_th/weights_best.h5",
  "stardist_models/stardist_psyn/config.json",
  "stardist_models/stardist_psyn/thresholds.json",
  "stardist_models/stardist_psyn/weights_best.h5",

  "stardist_models/2026.04.21_stardist_th_cam/config.json",
  "stardist_models/2026.04.21_stardist_th_cam/thresholds.json",
  "stardist_models/2026.04.21_stardist_th_cam/weights_best.h5",
  "stardist_models/2026.04.21_stardist_psyn_cam/config.json",
  "stardist_models/2026.04.21_stardist_psyn_cam/thresholds.json",
  "stardist_models/2026.04.21_stardist_psyn_cam/weights_best.h5",

  "stardist_models/2026.04.21-06.10_stardist_th_cam/config.json",
  "stardist_models/2026.04.21-06.10_stardist_th_cam/thresholds.json",
  "stardist_models/2026.04.21-06.10_stardist_th_cam/weights_best.h5",
  "stardist_models/2026.04.21-06.10_stardist_psyn_cam/config.json",
  "stardist_models/2026.04.21-06.10_stardist_psyn_cam/thresholds.json",
  "stardist_models/2026.04.21-06.10_stardist_psyn_cam/weights_best.h5",

]

[project.entry-points."napari.manifest"]
napari-bruce = "napari_bruce:napari.yaml"

[project.scripts]
bruce = "napari_bruce.cli:cli_main"

